### ISSUE TITLE
Listing the status of owned packages

### ISSUE THREAD

**Issue by gu1ll0me** [ccr-tools/python-ccr#9]

**Comment by gu1ll0me** [comment]
For this funcionnality, is that good for you if the module returns, as JSON format, the same informations contained in the My Packages page?

**Comment by rshipp** [comment]
Would this be the same format as the rest of the static methods, using [_get_ccr_json](https://github.com/ccr-tools/python-ccr/blob/development/ccr/ccr.py#L48)?

**Comment by gu1ll0me** [comment]
Yes. In fact, the msearch() function already do this job. We can have all the information about the status of owned packages with it. What was your idea about a function listing the "status" of owned packages? Should it includes all the information on the My Packages pages or a more precise information like just votes and out-of-date status?

Also, i would like to try to code a function that can tell if an updated version of the software is available on the source repository. If the pkgver is 13.0.2, i could try to check for 13.0.3 or 13.1.0 or 14.0.0. I think it could be helpful. What do you think?

**Comment by rshipp** [comment]
I'm not sure, what's the use case for this?

For updates, are you talking about upstream updates to CCR packages, or updates to the python-ccr code, or what?

**Comment by gu1ll0me** [comment]
Inkane asks me to add this functionnality some weeks ago. I will ask him for more details.

For updates, it is for upstream updates to CCR packages.

**Comment by Inkane** [comment]
The use case I saw for this is listing the status of ones own packages; that is, whether they are flagged as out of date, how many votes a package has, etc.
This would allow a GUI to display the information that can be found on the My packages page, without actually loading, parsing and displaying the HTML.

**Comment by rshipp** [comment]
Then I guess it might as well provide all info on the My Packages page. 

For updates, I was working on something similar at one point, you can see it [here](https://github.com/george2/pkgbuilds/blob/master/ccr-manage) and [here](https://github.com/george2/pkgbuilds/blob/master/ccr-manage-conf). It works well if you add rules to the config as you create each new package, or if you only have a few packages to add, but with a few hundred packages it takes a lot of work. Most of the rules are pretty similar, so the script could probably be made smarter, possibly even build the config itself automagically. I suppose you could also just try incrementing the version number and HTTP HEAD the upstream sources, but a lot of packages are pretty spastic about their versioning schemes, so that wouldn't work all the time.

**Comment by rshipp** [comment]
No method exists for this in the current CCR webapp. I'm closing the issue, feel free to reopen if this changes.

**Comment by rshipp** [comment]
This can already be accomplished by simply calling `msearch` and passing your ID. Since the ID is not known by the library (and should not be), I believe adding any more specific method is out of the scope of the library. This could instead be implemented as a feature of a CLI using the library.
